# Generated by Django 3.2.8 on 2021-11-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('time', models.TextField()),
                ('description', models.TextField()),
                ('cout_people', models.BigIntegerField()),
                ('place', models.TextField()),
                ('type', models.TextField()),
                ('is_public', models.BooleanField(default = True)),
            ],
            options={
                'verbose_name': 'Івенти',
            },
        ),
    ]
